## 200037 IM level2 因子  ## 200036 bar 分钟因子
## 规则 6位数，1XXYYY，XX为 品种的序号，YYY 为不同任务情况
[GENTIC_INDEX]

IF=200017
IC=140002
IM=200037
RB=113001
HC=134001
M =104001

[DATA_KIND]
200037 = 'level2'
200036 = 'basic'
113001 = 'basic'
140001 = 'basic'
140002 = 'level2'
134001 = 'basic'
104001 = 'basic'

[PERFORMANCE]
113001 = 'profit_sharpe'
200036 = "profit_sharpe"
200037 = "profit_sharpe"


[THRESHOLD]
200017 = 0.0
200037 = 1.0

[FILTER_YEAR]
IM = [['2024-01-25', '2024-02-06'], ['2024-09-24', '2024-10-11']]

[CONT_MULTNUM]
RB=10
HC=10
M=10
IF=300
IM=200

[COST]
RB=0.00005
IF=0.000023
IM=0.000012
HC=0.00005
M = 0.0000

[COST_MODE]
RB="rate"
IM="rate"
HC="rate"

[SLIPPAGE]
RB=0
IF=0.0001
IM=0#1.7e-07
HC=0

[INSTRUMENTS]
rbb="RB"
ims="IM"
ics="IC"
ifs="IF"
mc="M"
hcb = "HC"

