[CONT_MULTNUM]
RB = 10
IM = 200
IF = 300
M = 10
AU = 1000

[MAIN_CONTRACT]
RB = 'rb2510'
IM = 'IM2509'
IF = 'IF2509'
M = 'm2509'
AU = 'au2506'

[SYMBOL_CONTRANCT]
rb2510 = 'RB'
IM2506 = 'IM'
IF2506 = 'IF'
m2509 = 'M'
au2506 = 'AU'

[CHAOS_PHECDA]
#au2506 = '1024730794'
IM2506 = '1078761302'

[CHAOS_VIRGTOR]
IM2506 = '1059861670'

[KICHAOS_VIRGTOR]
1059861670 = 'sac_base_hedge041'


[OPTIONS_SPOT]
MO = 'IF'
